from __future__ import annotations

import json
import os
from typing import Any

from daily_report.models import LLMConfig, SectionConfig


class SectionWriter:
    def __init__(self, llm_config: LLMConfig, language: str) -> None:
        self._llm_config = llm_config
        self._language = language

    def write(self, section: SectionConfig, context: dict[str, Any]) -> str:
        api_key = os.getenv("OPENAI_API_KEY", "").strip()
        if api_key:
            rendered = self._write_with_openai(section=section, context=context, api_key=api_key)
            if rendered:
                return rendered

        return self._write_fallback(section=section, context=context)

    def _write_with_openai(self, section: SectionConfig, context: dict[str, Any], api_key: str) -> str:
        try:
            from openai import OpenAI
        except ImportError:
            return ""

        prompt = (
            "You are a real-estate market analyst. "
            f"Write this section in {self._language}. "
            "Return valid markdown only, and do not repeat the section title.\n\n"
            f"Section title: {section.title}\n"
            f"Instruction: {section.instruction}\n"
            f"Context JSON:\n{json.dumps(context, ensure_ascii=False, default=str)}"
        )

        try:
            client = OpenAI(api_key=api_key)
            response = client.responses.create(
                model=self._llm_config.model,
                temperature=self._llm_config.temperature,
                input=prompt,
            )
            text = response.output_text.strip()
            return text
        except Exception:
            return ""

    def _write_fallback(self, section: SectionConfig, context: dict[str, Any]) -> str:
        if section.id == "policy_news":
            items = context.get("news_items", [])
            if not items:
                return "- No policy news found in this time window."
            lines = ["- Key policy headlines:"]
            for item in items[:8]:
                lines.append(
                    f"  - [{item['title']}]({item['link']}) ({item['source']}, {item['published_at']})"
                )
            return "\n".join(lines)

        if section.id == "price_trend":
            metrics = context.get("metrics", [])
            if not metrics:
                return "- No market metrics available."
            lines = ["| Region | Asset | Avg Price | D-1 | W-1 | Txn | Txn D-1 |", "|---|---:|---:|---:|---:|---:|---:|"]
            for metric in metrics:
                lines.append(
                    "| {region} | {asset} | {price:.2f} | {d:+.2f}% | {w:+.2f}% | {txn} | {td:+.2f}% |".format(
                        region=metric["region_name"],
                        asset=metric["asset"],
                        price=metric["current_avg_price"],
                        d=metric["daily_change_pct"],
                        w=metric["weekly_change_pct"],
                        txn=metric["current_txn_count"],
                        td=metric["txn_daily_change_pct"],
                    )
                )
            return "\n".join(lines)

        if section.id == "insights":
            movers = context.get("top_movers", [])
            if not movers:
                return "- Not enough signals for additional insights today."
            lines = ["- Notable movers:"]
            for mover in movers:
                lines.append(
                    "  - {region} {asset}: price {change:+.2f}% d/d, {week:+.2f}% w/w, txn {txn_change:+.2f}% d/d".format(
                        region=mover["region_name"],
                        asset=mover["asset"],
                        change=mover["daily_change_pct"],
                        week=mover["weekly_change_pct"],
                        txn_change=mover["txn_daily_change_pct"],
                    )
                )
            lines.append("- Caveat: synthetic sample data is used when public API configuration is missing or unavailable.")
            return "\n".join(lines)

        return "- Section generated by fallback writer."
